/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplitRouteImport } from './routes/split'
import { Route as PdfToJpgRouteImport } from './routes/pdf-to-jpg'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as ExtractImagesRouteImport } from './routes/extract-images'
import { Route as CompressRouteImport } from './routes/compress'
import { Route as IndexRouteImport } from './routes/index'

const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToJpgRoute = PdfToJpgRouteImport.update({
  id: '/pdf-to-jpg',
  path: '/pdf-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractImagesRoute = ExtractImagesRouteImport.update({
  id: '/extract-images',
  path: '/extract-images',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressRoute = CompressRouteImport.update({
  id: '/compress',
  path: '/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/extract-images': typeof ExtractImagesRoute
  '/merge': typeof MergeRoute
  '/pdf-to-jpg': typeof PdfToJpgRoute
  '/split': typeof SplitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/extract-images': typeof ExtractImagesRoute
  '/merge': typeof MergeRoute
  '/pdf-to-jpg': typeof PdfToJpgRoute
  '/split': typeof SplitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/extract-images': typeof ExtractImagesRoute
  '/merge': typeof MergeRoute
  '/pdf-to-jpg': typeof PdfToJpgRoute
  '/split': typeof SplitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compress'
    | '/extract-images'
    | '/merge'
    | '/pdf-to-jpg'
    | '/split'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compress'
    | '/extract-images'
    | '/merge'
    | '/pdf-to-jpg'
    | '/split'
  id:
    | '__root__'
    | '/'
    | '/compress'
    | '/extract-images'
    | '/merge'
    | '/pdf-to-jpg'
    | '/split'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompressRoute: typeof CompressRoute
  ExtractImagesRoute: typeof ExtractImagesRoute
  MergeRoute: typeof MergeRoute
  PdfToJpgRoute: typeof PdfToJpgRoute
  SplitRoute: typeof SplitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-jpg': {
      id: '/pdf-to-jpg'
      path: '/pdf-to-jpg'
      fullPath: '/pdf-to-jpg'
      preLoaderRoute: typeof PdfToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract-images': {
      id: '/extract-images'
      path: '/extract-images'
      fullPath: '/extract-images'
      preLoaderRoute: typeof ExtractImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress': {
      id: '/compress'
      path: '/compress'
      fullPath: '/compress'
      preLoaderRoute: typeof CompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompressRoute: CompressRoute,
  ExtractImagesRoute: ExtractImagesRoute,
  MergeRoute: MergeRoute,
  PdfToJpgRoute: PdfToJpgRoute,
  SplitRoute: SplitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
